# Logictic reegresion with multiclass implementation

In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline


In [17]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression


In [18]:
X,y= make_classification(n_samples = 1000,n_features=10, n_informative=3 ,n_classes= 3, random_state= 15 )

In [19]:
y

array([2, 0, 0, 0, 1, 0, 1, 0, 2, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 2,
       2, 1, 1, 0, 2, 0, 2, 1, 2, 1, 2, 2, 0, 1, 2, 1, 1, 2, 1, 1, 2, 2,
       0, 2, 1, 0, 2, 0, 0, 1, 0, 1, 1, 0, 2, 2, 0, 1, 1, 2, 0, 0, 1, 0,
       0, 1, 2, 2, 0, 1, 2, 2, 1, 2, 0, 2, 0, 0, 1, 0, 2, 0, 2, 0, 0, 2,
       1, 2, 0, 0, 2, 0, 1, 0, 2, 0, 2, 1, 0, 0, 2, 2, 0, 2, 2, 0, 1, 0,
       1, 0, 1, 2, 1, 1, 1, 2, 0, 2, 0, 2, 1, 1, 0, 0, 1, 1, 2, 2, 1, 2,
       0, 1, 2, 2, 0, 2, 2, 0, 0, 1, 0, 2, 0, 1, 2, 0, 2, 1, 1, 0, 2, 1,
       0, 2, 2, 2, 2, 2, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       2, 2, 1, 2, 2, 2, 2, 0, 1, 0, 1, 0, 2, 2, 2, 1, 1, 0, 0, 0, 2, 0,
       0, 0, 1, 0, 2, 1, 0, 2, 2, 1, 1, 1, 1, 2, 0, 1, 2, 2, 1, 1, 0, 2,
       2, 1, 0, 2, 2, 1, 0, 1, 2, 0, 2, 1, 0, 0, 1, 2, 0, 0, 0, 0, 2, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 2, 2, 1, 0, 1, 1, 2, 2, 2, 2, 0, 1, 0,
       0, 2, 2, 1, 2, 0, 0, 1, 1, 2, 2, 1, 0, 0, 1, 0, 1, 2, 1, 0, 1, 0,
       2, 0, 1, 0, 0, 2, 2, 1, 0, 2, 0, 1, 2, 2, 2,

In [25]:
from sklearn.model_selection import train_test_split


In [26]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.3, random_state=42)

In [27]:
X_train.shape, X_test.shape

((700, 10), (300, 10))

In [41]:
from sklearn.multiclass import OneVsRestClassifier


In [46]:
model = LogisticRegression()
ovr = OneVsRestClassifier(estimator=model)


In [48]:
ovr.fit(X_train,Y_train)
y_pred = ovr.predict(X_test)



In [50]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [52]:
print(accuracy_score(Y_test,y_pred))
print(classification_report(Y_test,y_pred))
print(confusion_matrix(y_pred,Y_test))


0.79
              precision    recall  f1-score   support

           0       0.87      0.82      0.84       102
           1       0.81      0.73      0.77       102
           2       0.71      0.82      0.76        96

    accuracy                           0.79       300
   macro avg       0.79      0.79      0.79       300
weighted avg       0.80      0.79      0.79       300

[[84  3 10]
 [10 74  7]
 [ 8 25 79]]


## logistic regression for imbalance dataset

In [53]:
from collections import Counter
from sklearn.datasets import make_classification

In [55]:
X,Y = make_classification(n_samples=1000,n_informative=3, n_clusters_per_class=1,n_redundant=0,weights=[0.99],random_state=42, n_features=3)

In [56]:
X,Y

(array([[-0.80801559,  1.32539269, -1.96441537],
        [-0.75282819,  0.60389302, -1.66770026],
        [-1.02530862,  0.81632358, -0.82988781],
        ...,
        [-0.80200997,  0.183799  , -0.17538624],
        [-0.99592417,  1.36948124, -1.39071635],
        [-0.88095639,  0.16587132, -0.51812914]], shape=(1000, 3)),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        

In [58]:
Counter(Y)

Counter({np.int64(0): 985, np.int64(1): 15})

In [61]:
sns.scatterplot(X = pd.DataFrame(X)[0],pd.DataFrame(X)[1],hue = Y)

SyntaxError: positional argument follows keyword argument (1449930271.py, line 1)